### PR TITLE
Add core_version_requirement

### PR DESCRIPTION
**Pull request by arnested**
See https://www.drupal.org/node/3070687.

### CODE REVIEW

**Comment by Chi-teck** [comment]
Shouldn't `core_version_requirement` be required?

**Comment by arnested** [comment]
No.

Modules can still use just `core` or they can use the new one. Or both. All depending on which versions they have to support (I guess it's because they can't get people to transition all at once anyway). 

That's also why I had to remove `core` as a requirement.

**Comment by Chi-teck** [comment]
Here is my understanding of that change record:

version | core | core_version_requirement
 :---: | :---:  |  :---: 
\< 8.7.6 |  :heavy_check_mark: | :x:
\> 8.7.7 \< 9.0.0 | :white_check_mark: | :heavy_check_mark: 
\> 9.0.0 | :white_check_mark: | :heavy_check_mark:

:heavy_check_mark: – Supported
:white_check_mark: – Supported but not recommended
:x: – Not supported

From this point for 8.7.6 < Drupal < 9.0.0 extensions must specify at least one of these keys (`core_version_requirement` is preferable).

Let me know if I am mistaken.

**Comment by arnested** [comment]
Correct (after the edit :-)

**Comment by Chi-teck** [comment]
So I propose we make `core_version_requirement` key required. It makes sense to have this key even for extensions that run on Drupal < 8.7.7 as they will eventually have to be updated.

Overall this issue raises the question of possible incompatibility JSON schemes between Drupal 8 and Drupal 9. I think we need to create a new branch for Drupal 9.

**Comment by arnested** [comment]
Yeah, adding `core_version_requirement` as  a requirement could be the way forward. Modules that will be kept left behind probably won't be edited anyway.

With a branch for Drupal 9 would you then release a different schema for D9? Because, that would probably be annoying for people working with both versions?

**Comment by Chi-teck** [comment]
>  Because, that would probably be annoying for people working with both versions?

The schemes are installed per project not globally. We can keep single branch as long as Drupal 9 schemes are compatible with Drupal 8.

**Comment by Chi-teck** [comment]
Thank you.

**Comment by arnested** [comment]
And thank you for making this in the first place.

> The schemes are installed per project not globally.

I haven't tweak my Emacs to perfection with this yet, but it's probably a global install in Emacs.

**Comment by Chi-teck** [comment]
Well, I only considered PhpStorm. Good to know that there is other Drupal IDEs/editors that support JSON schema.

**Pull request merged**
